version: "3.1"

services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./php/services:/srv/www/services
      - ./static:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    stdin_open: true
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - php
      - nodejs

  db:
    container_name: database
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'lamoda'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - .:/php/db/dump/init.sql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '80:80'
    environment:
      MYSQL_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=password
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  nodejs:
    container_name: frontend
    build: ./nodejs
    environment:
     - NODE_ENV=production
     - HOST=0.0.0.0
     - CHOKIDAR_USEPOLLING=true
    working_dir: /home/app
    restart: always
    volumes:
      - ./nodejs:/home/app
    depends_on:
      - php
    #command: npm start
    links:
      - redis

  php:
    container_name: backend
    build: ./php
    links:
      - db
    volumes:
      - .:/var/www/html

  redis:
    image: redis:alpine
    volumes:
      - /var/redis/data:/data

networks:
  mysql-phpmyadmin:

volumes:
  my-db:
